### ISSUE TITLE
It Keep Showing me " no Result" 

### ISSUE THREAD

**Issue by Deku-izuku-dotcom** [deepseagirl/degoogle#1]
after try  the tool it keep showing ' no result ' message . 
![Test](https://user-images.githubusercontent.com/55627732/101987013-cd773c00-3c91-11eb-8a6c-335c524e31c8.png)

**Comment by deepseagirl** [comment]
unfortunately it's difficult to debug this, because we don't fully understand why this tool works in the first place :(

Sometimes, certain devices seem to have a bad enough "reputation" with google that it already hits a captcha before you get any results - other devices never have a problem. more research may find us the answer to why this is. _(edit to add: this concept of a "reputation" is only my attempt to describe my observations. it could come down to something as simple as having an IP from a certain region or provider, or anything else unique about you. take that term with a grain of salt)_

so, can you try on another device? My results for the same query you ran:
![image](https://user-images.githubusercontent.com/47490856/102020007-80a06d80-3d44-11eb-80a8-ef5de3d7cd45.png)

**Comment by Deku-izuku-dotcom** [comment]
Okey Thanks for your Clarification

**Comment by fiuderazes** [comment]
Same problem, I cannot overpass it at all.
